/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import Evento.Combobox.EvenCombobox;
import Evento.Fecha.EvenFecha;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import Evento.Jtable.EvenRender;
import FILTRO.ClaAuxFiltroVenta;
import FORMULARIO.DAO.DAO_usuario;
import FORMULARIO.DAO.DAO_venta;
//import FORMULARIO.DAO.DAO_cliente;
//import FORMULARIO.DAO.DAO_venta_alquiler;
//import FORMULARIO.ENTIDAD.cliente;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Digno
 */
public class FrmRepOcupacion extends javax.swing.JInternalFrame {

    private String nombre_formulario = "REPORTE OCUPACION";
    private EvenJFRAME evetbl = new EvenJFRAME();
    private Connection conn = ConnPostgres.getConnPosgres();
    private EvenJtable evejt = new EvenJtable();
    private EvenFecha evefec = new EvenFecha();
    private ClaAuxFiltroVenta auxvent = new ClaAuxFiltroVenta();
    private EvenJTextField evejtf = new EvenJTextField();
    private EvenConexion eveconn = new EvenConexion();
    private EvenRender everende = new EvenRender();
    private DAO_venta DAOven=new DAO_venta();
    private EvenCombobox evecmb=new EvenCombobox();
    private DAO_usuario DAOusu = new DAO_usuario();
    private void abrir_formulario() {
        this.setTitle(nombre_formulario);
        evetbl.centrar_formulario_internalframa(this);
        reestableser();
//        actualizar_tabla();
    }
    private String filtro_ocupacion(int tipo){
        String filtro="";
        String fecDesde=evefec.getfechaDCStringFormat(dcfecDesde,"yyyy-MM-dd");
        String fecHasta=evefec.getfechaDCStringFormat(dcfecHasta,"yyyy-MM-dd");
        String filtro_fecha="and date(hr.fec_ocupado_fin)>='"+fecDesde+"' and date(hr.fec_ocupado_fin)<='"+fecHasta+"' ";
        String filtro_hab="";
        String filtro_usu="";
        String filtro_fecha2="Fecha Desde: "+fecDesde+" Hasta: "+fecHasta+" ";
        String filtro_hab2="";
        String filtro_usu2="";
        if(cmbnro_habitacion.getSelectedIndex()>0){
            String nro_habitacion=cmbnro_habitacion.getSelectedItem().toString();
            filtro_hab="and concat(hr.nro_habitacion,'-(',hd.tipo_habitacion,')')='"+nro_habitacion+"' ";
            filtro_hab2=" HAB: "+nro_habitacion;
        }
        if(cmbusuario2.getSelectedIndex()>0){
            int idusuario=DAOusu.getInt_idusuario_combo(conn, cmbusuario2);
            filtro_usu="and u.idusuario="+idusuario+" ";
            filtro_usu2=" Usuario:"+cmbusuario2.getSelectedItem().toString();
        }
        if(tipo==1){
            filtro=filtro_fecha+filtro_hab+filtro_usu;
        }
        if(tipo==2){
            filtro=filtro_fecha2+filtro_hab2+filtro_usu2;
        }
        return filtro;
    }
    private void actualizar_tabla() {
        
        DAOven.actualizar_tabla_filtro_venta(conn, tblfiltro_ocupacion, filtro_ocupacion(1));
        double monto_minimo = evejt.getDouble_sumar_tabla(tblfiltro_ocupacion, 13);
        double monto_adicional = evejt.getDouble_sumar_tabla(tblfiltro_ocupacion, 14);
        double monto_consumo = evejt.getDouble_sumar_tabla(tblfiltro_ocupacion, 15);
        double monto_total = evejt.getDouble_sumar_tabla(tblfiltro_ocupacion, 16);
        jFmonto_minimo.setValue(monto_minimo);
        jFmonto_adicional.setValue(monto_adicional);
        jFmonto_consumo.setValue(monto_consumo);
        jFmonto_total.setValue(monto_total);
        int cant=tblfiltro_ocupacion.getRowCount();
        jFcantidad.setValue(cant);
    }

    private void reestableser() {
        evefec.setFechaDCSistema(dcfecDesde);
        evefec.setFechaDCSistema(dcfecHasta);
        evecmb.cargarCombobox_orden(conn, cmbnro_habitacion,"tipo_habitacion","nro_habitacion","habitacion_dato","where activo=true","order by nro_habitacion asc");
        DAOusu.cargar_usuario_combo(conn, cmbusuario2);
    }
    private void boton_filtro_ocupacion_imprimir() {
        DAOven.imprimir_filtro_venta(conn, filtro_ocupacion(1), filtro_ocupacion(2));
    }
    public FrmRepOcupacion() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfiltro_ocupacion = new javax.swing.JTable();
        jFmonto_minimo = new javax.swing.JFormattedTextField();
        jFmonto_adicional = new javax.swing.JFormattedTextField();
        jFmonto_consumo = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        btnbuscar_fecha = new javax.swing.JButton();
        dcfecDesde = new com.toedter.calendar.JDateChooser();
        dcfecHasta = new com.toedter.calendar.JDateChooser();
        cmbnro_habitacion = new javax.swing.JComboBox<>();
        cmbusuario2 = new javax.swing.JComboBox<>();
        btnimprimir_filtro_ocupacion = new javax.swing.JButton();
        jFmonto_total = new javax.swing.JFormattedTextField();
        jFcantidad = new javax.swing.JFormattedTextField();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("TABLA OCUPACION"));

        tblfiltro_ocupacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblfiltro_ocupacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        jFmonto_minimo.setEditable(false);
        jFmonto_minimo.setBackground(new java.awt.Color(255, 255, 255));
        jFmonto_minimo.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO MINIMO:"));
        jFmonto_minimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFmonto_minimo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jFmonto_adicional.setEditable(false);
        jFmonto_adicional.setBackground(new java.awt.Color(255, 255, 255));
        jFmonto_adicional.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO ADICIONAL:"));
        jFmonto_adicional.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFmonto_adicional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jFmonto_consumo.setEditable(false);
        jFmonto_consumo.setBackground(new java.awt.Color(255, 255, 255));
        jFmonto_consumo.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO CONSUMO:"));
        jFmonto_consumo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFmonto_consumo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO OCUPACION"));

        btnbuscar_fecha.setText("BUSCAR");
        btnbuscar_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar_fechaActionPerformed(evt);
            }
        });

        dcfecDesde.setBorder(javax.swing.BorderFactory.createTitledBorder("DESDE:"));
        dcfecDesde.setDateFormatString("yyyy-MM-dd");
        dcfecDesde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dcfecHasta.setBorder(javax.swing.BorderFactory.createTitledBorder("HASTA:"));
        dcfecHasta.setDateFormatString("yyyy-MM-dd");
        dcfecHasta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cmbnro_habitacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbnro_habitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbnro_habitacion.setBorder(javax.swing.BorderFactory.createTitledBorder("HABITACION:"));
        cmbnro_habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnro_habitacionActionPerformed(evt);
            }
        });

        cmbusuario2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbusuario2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbusuario2.setBorder(javax.swing.BorderFactory.createTitledBorder("USUARIO:"));
        cmbusuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbusuario2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dcfecDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcfecHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbnro_habitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcfecDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(dcfecHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbnro_habitacion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbusuario2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnbuscar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        btnimprimir_filtro_ocupacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta/ven_imprimir.png"))); // NOI18N
        btnimprimir_filtro_ocupacion.setText("FILTRO OCUPACION");
        btnimprimir_filtro_ocupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_filtro_ocupacionActionPerformed(evt);
            }
        });

        jFmonto_total.setEditable(false);
        jFmonto_total.setBackground(new java.awt.Color(255, 255, 255));
        jFmonto_total.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO TOTAL:"));
        jFmonto_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFmonto_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jFcantidad.setEditable(false);
        jFcantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("CANT:"));
        jFcantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFcantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnimprimir_filtro_ocupacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmonto_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmonto_adicional, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmonto_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmonto_total, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFmonto_minimo)
                    .addComponent(jFmonto_adicional)
                    .addComponent(jFmonto_consumo)
                    .addComponent(jFmonto_total)
                    .addComponent(btnimprimir_filtro_ocupacion)
                    .addComponent(jFcantidad))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
//        DAOva.ancho_tabla_venta_alquiler_rep_1(tblfiltro_venta_alquiler);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnbuscar_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar_fechaActionPerformed
        // TODO add your handling code here:
        actualizar_tabla();
    }//GEN-LAST:event_btnbuscar_fechaActionPerformed

    private void btnimprimir_filtro_ocupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_filtro_ocupacionActionPerformed
        // TODO add your handling code here:
        boton_filtro_ocupacion_imprimir();
    }//GEN-LAST:event_btnimprimir_filtro_ocupacionActionPerformed

    private void cmbusuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbusuario2ActionPerformed
        // TODO add your handling code here:
         actualizar_tabla();
    }//GEN-LAST:event_cmbusuario2ActionPerformed

    private void cmbnro_habitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnro_habitacionActionPerformed
        // TODO add your handling code here:
         actualizar_tabla();
    }//GEN-LAST:event_cmbnro_habitacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar_fecha;
    private javax.swing.JButton btnimprimir_filtro_ocupacion;
    private javax.swing.JComboBox<String> cmbnro_habitacion;
    private javax.swing.JComboBox<String> cmbusuario2;
    private com.toedter.calendar.JDateChooser dcfecDesde;
    private com.toedter.calendar.JDateChooser dcfecHasta;
    private javax.swing.JFormattedTextField jFcantidad;
    private javax.swing.JFormattedTextField jFmonto_adicional;
    private javax.swing.JFormattedTextField jFmonto_consumo;
    private javax.swing.JFormattedTextField jFmonto_minimo;
    private javax.swing.JFormattedTextField jFmonto_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfiltro_ocupacion;
    // End of variables declaration//GEN-END:variables
}
