/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import ESTADOS.EvenEstado;
import Evento.Combobox.EvenCombobox;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import FORMULARIO.BO.BO_producto;
import FORMULARIO.DAO.DAO_producto;
import FORMULARIO.ENTIDAD.producto;
import FORMULARIO.ENTIDAD.usuario;
import java.sql.Connection;
import javax.swing.JTable;

/**
 *
 * @author Digno
 */
public class JDiaBuscarProducto extends javax.swing.JDialog {

    private EvenJFRAME evetbl = new EvenJFRAME();
    private EvenJtable eveJtab = new EvenJtable();
    private producto ENTpro = new producto();
    private DAO_producto DAOper = new DAO_producto();
    private BO_producto BOper = new BO_producto();
    private EvenJTextField evejtf = new EvenJTextField();
    private EvenCombobox evecmb = new EvenCombobox();
    private EvenEstado eveest = new EvenEstado();
    private EvenConexion eveconn = new EvenConexion();
    Connection conn = ConnPostgres.getConnPosgres();
    usuario ENTusu = new usuario();
    private String nombreTabla_pri = "PRODUCTO";
    private String nombreTabla_sec = "FILTRO";
    private String creado_por = "digno";

    private void abrir_formulario() {
        this.setTitle(nombreTabla_pri);
//        evetbl.centrar_formulario_internalframa(this);  
        creado_por = ENTusu.getGlobal_nombre();
        actualizar_tabla_producto(0);
    }

    private void actualizar_tabla_producto(int tipo) {
        String buscar = "";
        if (tipo == 1) {
            if (txtbusca_nombre.getText().trim().length() > 2) {
                String nombre = txtbusca_nombre.getText();
                buscar = " and p.nombre ilike'%" + nombre + "%' ";
            }
        }
        String sql = "select p.idproducto as idp,\n"
                + "(p.nombre) as producto,u.nombre as unidad,p.iva as iva,\n"
                + "TRIM(to_char(p.precio_interno,'999G999G999')) as pventa,\n"
                + "p.precio_interno as oculto_venta \n"
                + "from producto p,producto_categoria c,producto_unidad u,producto_marca pm \n"
                + "where p.fk_idproducto_categoria=c.idproducto_categoria \n"
                + "and p.fk_idproducto_unidad=u.idproducto_unidad \n"
                + "and p.fk_idproducto_marca=pm.idproducto_marca \n"
                + "and c.activo=true \n"
                + "and p.es_venta=true \n"+buscar
                + " order by p.idproducto  asc;";

        eveconn.Select_cargar_jtable(conn, sql, tblbuscarproducto);
        ancho_tabla();
    }

    private void ancho_tabla() {
        int Ancho[] = {5, 50,15, 5, 15, 1};
        eveJtab.setAnchoColumnaJtable(tblbuscarproducto, Ancho);
        eveJtab.ocultar_columna(tblbuscarproducto,5);
        eveJtab.alinear_derecha_columna(tblbuscarproducto,4);
    }

    private void seleccionar_tabla() {
        if (tblbuscarproducto.getSelectedRow() >= 0) {
            int idproducto = eveJtab.getInt_select_id(tblbuscarproducto);
            String producto = eveJtab.getString_select(tblbuscarproducto, 1);
//            String direccion = eveJtab.getString_select(tblbuscarproducto, 2);
            String iva = eveJtab.getString_select(tblbuscarproducto, 3);
            String precio = eveJtab.getString_select(tblbuscarproducto,5);
            ENTpro.setIdproducto_global(idproducto);
            ENTpro.setIva_global(Integer.parseInt(iva));
            FrmFactura.txtitem_nombre.setText(producto);
            FrmFactura.txtitem_cantidad.setText("1");
            String precio_format=evejtf.getString_format_nro_decimal(precio);
            FrmFactura.txtitem_precio.setText(precio_format);
            FrmFactura.txtitem_subtotal.setText(precio_format);
        }
    }

    public void ancho_tabla_producto(JTable tbltabla) {
        int Ancho[] = {5, 50, 15, 15, 15};
        eveJtab.setAnchoColumnaJtable(tbltabla, Ancho);
    }

    public JDiaBuscarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbuscarproducto = new javax.swing.JTable();
        txtbusca_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR PRODUCTO"));

        tblbuscarproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbuscarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblbuscarproductoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblbuscarproducto);

        txtbusca_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtbusca_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusca_nombreKeyReleased(evt);
            }
        });

        jButton1.setText("SELECCIONAR Y SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtbusca_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtbusca_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblbuscarproductoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbuscarproductoMouseReleased
        // TODO add your handling code here:
        seleccionar_tabla();
    }//GEN-LAST:event_tblbuscarproductoMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        seleccionar_tabla();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbusca_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusca_nombreKeyReleased
        // TODO add your handling code here:
        actualizar_tabla_producto(1);
    }//GEN-LAST:event_txtbusca_nombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDiaBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDiaBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDiaBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDiaBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDiaBuscarProducto dialog = new JDiaBuscarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbuscarproducto;
    private javax.swing.JTextField txtbusca_nombre;
    // End of variables declaration//GEN-END:variables
}
